
import React from 'react'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '../ui/dropdown-menu';
import { Button } from '../ui/button';
import { ChevronDown } from 'lucide-react';
interface CountrySelectedProps {
    value: string;
    onValueChange: (value: string) => void;
    disabled?: boolean
}
const countryList = [
	{ code: "AF", name: "Afghanistan", flag: "🇦🇫" },
	{ code: "AL", name: "Albania", flag: "🇦🇱" },
	{ code: "DZ", name: "Algeria", flag: "🇩🇿" },
	{ code: "AS", name: "American Samoa", flag: "🇦🇸" },
	{ code: "AD", name: "Andorra", flag: "🇦🇩" },
	{ code: "AO", name: "Angola", flag: "🇦🇴" },
	{ code: "AI", name: "Anguilla", flag: "🇦🇮" },
	{ code: "AQ", name: "Antarctica", flag: "🇦🇶" },
	{ code: "AG", name: "Antigua and Barbuda", flag: "🇦🇬" },
	{ code: "AR", name: "Argentina", flag: "🇦🇷" },
	{ code: "AM", name: "Armenia", flag: "🇦🇲" },
	{ code: "AW", name: "Aruba", flag: "🇦🇼" },
	{ code: "AU", name: "Australia", flag: "🇦🇺" },
	{ code: "AT", name: "Austria", flag: "🇦🇹" },
	{ code: "AZ", name: "Azerbaijan", flag: "🇦🇿" },
	{ code: "BS", name: "Bahamas (the)", flag: "🇧🇸" },
	{ code: "BH", name: "Bahrain", flag: "🇧🇭" },
	{ code: "BD", name: "Bangladesh", flag: "🇧🇩" },
	{ code: "BB", name: "Barbados", flag: "🇧🇧" },
	{ code: "BY", name: "Belarus", flag: "🇧🇾" },
	{ code: "BE", name: "Belgium", flag: "🇧🇪" },
	{ code: "BZ", name: "Belize", flag: "🇧🇿" },
	{ code: "BJ", name: "Benin", flag: "🇧🇯" },
	{ code: "BM", name: "Bermuda", flag: "🇧🇲" },
	{ code: "BT", name: "Bhutan", flag: "🇧🇹" },
	{ code: "BO", name: "Bolivia (Plurinational State of)", flag: "🇧🇴" },
	{ code: "BQ", name: "Bonaire, Sint Eustatius and Saba", flag: "🇧🇶" },
	{ code: "BA", name: "Bosnia and Herzegovina", flag: "🇧🇦" },
	{ code: "BW", name: "Botswana", flag: "🇧🇼" },
	{ code: "BV", name: "Bouvet Island", flag: "🇧🇻" },
	{ code: "BR", name: "Brazil", flag: "🇧🇷" },
	{ code: "IO", name: "British Indian Ocean Territory (the)", flag: "🇮🇴" },
	{ code: "BN", name: "Brunei Darussalam", flag: "🇧🇳" },
	{ code: "BG", name: "Bulgaria", flag: "🇧🇬" },
	{ code: "BF", name: "Burkina Faso", flag: "🇧🇫" },
	{ code: "BI", name: "Burundi", flag: "🇧🇮" },
	{ code: "CV", name: "Cabo Verde", flag: "🇨🇻" },
	{ code: "KH", name: "Cambodia", flag: "🇰🇭" },
	{ code: "CM", name: "Cameroon", flag: "🇨🇲" },
	{ code: "CA", name: "Canada", flag: "🇨🇦" },
	{ code: "KY", name: "Cayman Islands (the)", flag: "🇰🇾" },
	{ code: "CF", name: "Central African Republic (the)", flag: "🇨🇫" },
	{ code: "TD", name: "Chad", flag: "🇹🇩" },
	{ code: "CL", name: "Chile", flag: "🇨🇱" },
	{ code: "CN", name: "China", flag: "🇨🇳" },
	{ code: "CX", name: "Christmas Island", flag: "🇨🇽" },
	{ code: "CC", name: "Cocos (Keeling) Islands (the)", flag: "🇨🇨" },
	{ code: "CO", name: "Colombia", flag: "🇨🇴" },
	{ code: "KM", name: "Comoros (the)", flag: "🇰🇲" },
	{ code: "CD", name: "Congo (the Democratic Republic of the)", flag: "🇨🇩" },
	{ code: "CG", name: "Congo (the)", flag: "🇨🇬" },
	{ code: "CK", name: "Cook Islands (the)", flag: "🇨🇰" },
	{ code: "CR", name: "Costa Rica", flag: "🇨🇷" },
	{ code: "HR", name: "Croatia", flag: "🇭🇷" },
	{ code: "CU", name: "Cuba", flag: "🇨🇺" },
	{ code: "CW", name: "Curaçao", flag: "🇨🇼" },
	{ code: "CY", name: "Cyprus", flag: "🇨🇾" },
	{ code: "CZ", name: "Czechia", flag: "🇨🇿" },
	{ code: "CI", name: "Côte d'Ivoire", flag: "🇨🇮" },
	{ code: "DK", name: "Denmark", flag: "🇩🇰" },
	{ code: "DJ", name: "Djibouti", flag: "🇩🇯" },
	{ code: "DM", name: "Dominica", flag: "🇩🇲" },
	{ code: "DO", name: "Dominican Republic (the)", flag: "🇩🇴" },
	{ code: "EC", name: "Ecuador", flag: "🇪🇨" },
	{ code: "EG", name: "Egypt", flag: "🇪🇬" },
	{ code: "SV", name: "El Salvador", flag: "🇸🇻" },
	{ code: "GQ", name: "Equatorial Guinea", flag: "🇬🇶" },
	{ code: "ER", name: "Eritrea", flag: "🇪🇷" },
	{ code: "EE", name: "Estonia", flag: "🇪🇪" },
	{ code: "SZ", name: "Eswatini", flag: "🇸🇿" },
	{ code: "ET", name: "Ethiopia", flag: "🇪🇹" },
	{ code: "FK", name: "Falkland Islands (the) [Malvinas]", flag: "🇫🇰" },
	{ code: "FO", name: "Faroe Islands (the)", flag: "🇫🇴" },
	{ code: "FJ", name: "Fiji", flag: "🇫🇯" },
	{ code: "FI", name: "Finland", flag: "🇫🇮" },
	{ code: "FR", name: "France", flag: "🇫🇷" },
	{ code: "GF", name: "French Guiana", flag: "🇬🇫" },
	{ code: "PF", name: "French Polynesia", flag: "🇵🇫" },
	{ code: "TF", name: "French Southern Territories (the)", flag: "🇹🇫" },
	{ code: "GA", name: "Gabon", flag: "🇬🇦" },
	{ code: "GM", name: "Gambia (the)", flag: "🇬🇲" },
	{ code: "GE", name: "Georgia", flag: "🇬🇪" },
	{ code: "DE", name: "Germany", flag: "🇩🇪" },
	{ code: "GH", name: "Ghana", flag: "🇬🇭" },
	{ code: "GI", name: "Gibraltar", flag: "🇬🇮" },
	{ code: "GR", name: "Greece", flag: "🇬🇷" },
	{ code: "GL", name: "Greenland", flag: "🇬🇱" },
	{ code: "GD", name: "Grenada", flag: "🇬🇩" },
	{ code: "GP", name: "Guadeloupe", flag: "🇬🇵" },
	{ code: "GU", name: "Guam", flag: "🇬🇺" },
	{ code: "GT", name: "Guatemala", flag: "🇬🇹" },
	{ code: "GG", name: "Guernsey", flag: "🇬🇬" },
	{ code: "GN", name: "Guinea", flag: "🇬🇳" },
	{ code: "GW", name: "Guinea-Bissau", flag: "🇬🇼" },
	{ code: "GY", name: "Guyana", flag: "🇬🇾" },
	{ code: "HT", name: "Haiti", flag: "🇭🇹" },
	{ code: "HM", name: "Heard Island and McDonald Islands", flag: "🇭🇲" },
	{ code: "VA", name: "Holy See (the)", flag: "🇻🇦" },
	{ code: "HN", name: "Honduras", flag: "🇭🇳" },
	{ code: "HK", name: "Hong Kong", flag: "🇭🇰" },
	{ code: "HU", name: "Hungary", flag: "🇭🇺" },
	{ code: "IS", name: "Iceland", flag: "🇮🇸" },
	{ code: "IN", name: "India", flag: "🇮🇳" },
	{ code: "ID", name: "Indonesia", flag: "🇮🇩" },
	{ code: "IR", name: "Iran (Islamic Republic of)", flag: "🇮🇷" },
	{ code: "IQ", name: "Iraq", flag: "🇮🇶" },
	{ code: "IE", name: "Ireland", flag: "🇮🇪" },
	{ code: "IM", name: "Isle of Man", flag: "🇮🇲" },
	{ code: "IL", name: "Israel", flag: "🇮🇱" },
	{ code: "IT", name: "Italy", flag: "🇮🇹" },
	{ code: "JM", name: "Jamaica", flag: "🇯🇲" },
	{ code: "JP", name: "Japan", flag: "🇯🇵" },
	{ code: "JE", name: "Jersey", flag: "🇯🇪" },
	{ code: "JO", name: "Jordan", flag: "🇯🇴" },
	{ code: "KZ", name: "Kazakhstan", flag: "🇰🇿" },
	{ code: "KE", name: "Kenya", flag: "🇰🇪" },
	{ code: "KI", name: "Kiribati", flag: "🇰🇮" },
	{ code: "KP", name: "Korea (the Democratic People's Republic of)", flag: "🇰🇵" },
	{ code: "KR", name: "Korea (the Republic of)", flag: "🇰🇷" },
	{ code: "KW", name: "Kuwait", flag: "🇰🇼" },
	{ code: "KG", name: "Kyrgyzstan", flag: "🇰🇬" },
	{ code: "LA", name: "Lao People's Democratic Republic (the)", flag: "🇱🇦" },
	{ code: "LV", name: "Latvia", flag: "🇱🇻" },
	{ code: "LB", name: "Lebanon", flag: "🇱🇧" },
	{ code: "LS", name: "Lesotho", flag: "🇱🇸" },
	{ code: "LR", name: "Liberia", flag: "🇱🇷" },
	{ code: "LY", name: "Libya", flag: "🇱🇾" },
	{ code: "LI", name: "Liechtenstein", flag: "🇱🇮" },
	{ code: "LT", name: "Lithuania", flag: "🇱🇹" },
	{ code: "LU", name: "Luxembourg", flag: "🇱🇺" },
	{ code: "MO", name: "Macao", flag: "🇲🇴" },
	{ code: "MG", name: "Madagascar", flag: "🇲🇬" },
	{ code: "MW", name: "Malawi", flag: "🇲🇼" },
	{ code: "MY", name: "Malaysia", flag: "🇲🇾" },
	{ code: "MV", name: "Maldives", flag: "🇲🇻" },
	{ code: "ML", name: "Mali", flag: "🇲🇱" },
	{ code: "MT", name: "Malta", flag: "🇲🇹" },
	{ code: "MH", name: "Marshall Islands (the)", flag: "🇲🇭" },
	{ code: "MQ", name: "Martinique", flag: "🇲🇶" },
	{ code: "MR", name: "Mauritania", flag: "🇲🇷" },
	{ code: "MU", name: "Mauritius", flag: "🇲🇺" },
	{ code: "YT", name: "Mayotte", flag: "🇾🇹" },
	{ code: "MX", name: "Mexico", flag: "🇲🇽" },
	{ code: "FM", name: "Micronesia (Federated States of)", flag: "🇫🇲" },
	{ code: "MD", name: "Moldova (the Republic of)", flag: "🇲🇩" },
	{ code: "MC", name: "Monaco", flag: "🇲🇨" },
	{ code: "MN", name: "Mongolia", flag: "🇲🇳" },
	{ code: "ME", name: "Montenegro", flag: "🇲🇪" },
	{ code: "MS", name: "Montserrat", flag: "🇲🇸" },
	{ code: "MA", name: "Morocco", flag: "🇲🇦" },
	{ code: "MZ", name: "Mozambique", flag: "🇲🇿" },
	{ code: "MM", name: "Myanmar", flag: "🇲🇲" },
	{ code: "NA", name: "Namibia", flag: "🇳🇦" },
	{ code: "NR", name: "Nauru", flag: "🇳🇷" },
	{ code: "NP", name: "Nepal", flag: "🇳🇵" },
	{ code: "NL", name: "Netherlands (the)", flag: "🇳🇱" },
	{ code: "NC", name: "New Caledonia", flag: "🇳🇨" },
	{ code: "NZ", name: "New Zealand", flag: "🇳🇿" },
	{ code: "NI", name: "Nicaragua", flag: "🇳🇮" },
	{ code: "NE", name: "Niger (the)", flag: "🇳🇪" },
	{ code: "NG", name: "Nigeria", flag: "🇳🇬" },
	{ code: "NU", name: "Niue", flag: "🇳🇺" },
	{ code: "NF", name: "Norfolk Island", flag: "🇳🇫" },
	{ code: "MP", name: "Northern Mariana Islands (the)", flag: "🇲🇵" },
	{ code: "NO", name: "Norway", flag: "🇳🇴" },
	{ code: "OM", name: "Oman", flag: "🇴🇲" },
	{ code: "PK", name: "Pakistan", flag: "🇵🇰" },
	{ code: "PW", name: "Palau", flag: "🇵🇼" },
	{ code: "PS", name: "Palestine, State of", flag: "🇵🇸" },
	{ code: "PA", name: "Panama", flag: "🇵🇦" },
	{ code: "PG", name: "Papua New Guinea", flag: "🇵🇬" },
	{ code: "PY", name: "Paraguay", flag: "🇵🇾" },
	{ code: "PE", name: "Peru", flag: "🇵🇪" },
	{ code: "PH", name: "Philippines (the)", flag: "🇵🇭" },
	{ code: "PN", name: "Pitcairn", flag: "🇵🇳" },
	{ code: "PL", name: "Poland", flag: "🇵🇱" },
	{ code: "PT", name: "Portugal", flag: "🇵🇹" },
	{ code: "PR", name: "Puerto Rico", flag: "🇵🇷" },
	{ code: "QA", name: "Qatar", flag: "🇶🇦" },
	{ code: "MK", name: "Republic of North Macedonia", flag: "🇲🇰" },
	{ code: "RO", name: "Romania", flag: "🇷🇴" },
	{ code: "RU", name: "Russian Federation (the)", flag: "🇷🇺" },
	{ code: "RW", name: "Rwanda", flag: "🇷🇼" },
	{ code: "RE", name: "Réunion", flag: "🇷🇪" },
	{ code: "BL", name: "Saint Barthélemy", flag: "🇧🇱" },
	{ code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha", flag: "🇸🇭" },
	{ code: "KN", name: "Saint Kitts and Nevis", flag: "🇰🇳" },
	{ code: "LC", name: "Saint Lucia", flag: "🇱🇨" },
	{ code: "MF", name: "Saint Martin (French part)", flag: "🇲🇫" },
	{ code: "PM", name: "Saint Pierre and Miquelon", flag: "🇵🇲" },
	{ code: "VC", name: "Saint Vincent and the Grenadines", flag: "🇻🇨" },
	{ code: "WS", name: "Samoa", flag: "🇼🇸" },
	{ code: "SM", name: "San Marino", flag: "🇸🇲" },
	{ code: "ST", name: "Sao Tome and Principe", flag: "🇸🇹" },
	{ code: "SA", name: "Saudi Arabia", flag: "🇸🇦" },
	{ code: "SN", name: "Senegal", flag: "🇸🇳" },
	{ code: "RS", name: "Serbia", flag: "🇷🇸" },
	{ code: "SC", name: "Seychelles", flag: "🇸🇨" },
	{ code: "SL", name: "Sierra Leone", flag: "🇸🇱" },
	{ code: "SG", name: "Singapore", flag: "🇸🇬" },
	{ code: "SX", name: "Sint Maarten (Dutch part)", flag: "🇸🇽" },
	{ code: "SK", name: "Slovakia", flag: "🇸🇰" },
	{ code: "SI", name: "Slovenia", flag: "🇸🇮" },
	{ code: "SB", name: "Solomon Islands", flag: "🇸🇧" },
	{ code: "SO", name: "Somalia", flag: "🇸🇴" },
	{ code: "ZA", name: "South Africa", flag: "🇿🇦" },
	{ code: "GS", name: "South Georgia and the South Sandwich Islands", flag: "🇬🇸" },
	{ code: "SS", name: "South Sudan", flag: "🇸🇸" },
	{ code: "ES", name: "Spain", flag: "🇪🇸" },
	{ code: "LK", name: "Sri Lanka", flag: "🇱🇰" },
	{ code: "SD", name: "Sudan (the)", flag: "🇸🇩" },
	{ code: "SR", name: "Suriname", flag: "🇸🇷" },
	{ code: "SJ", name: "Svalbard and Jan Mayen", flag: "🇸🇯" },
	{ code: "SE", name: "Sweden", flag: "🇸🇪" },
	{ code: "CH", name: "Switzerland", flag: "🇨🇭" },
	{ code: "SY", name: "Syrian Arab Republic", flag: "🇸🇾" },
	{ code: "TW", name: "Taiwan", flag: "🇹🇼" },
	{ code: "TJ", name: "Tajikistan", flag: "🇹🇯" },
	{ code: "TZ", name: "Tanzania, United Republic of", flag: "🇹🇿" },
	{ code: "TH", name: "Thailand", flag: "🇹🇭" },
	{ code: "TL", name: "Timor-Leste", flag: "🇹🇱" },
	{ code: "TG", name: "Togo", flag: "🇹🇬" },
	{ code: "TK", name: "Tokelau", flag: "🇹🇰" },
	{ code: "TO", name: "Tonga", flag: "🇹🇴" },
	{ code: "TT", name: "Trinidad and Tobago", flag: "🇹🇹" },
	{ code: "TN", name: "Tunisia", flag: "🇹🇳" },
	{ code: "TR", name: "Turkey", flag: "🇹🇷" },
	{ code: "TM", name: "Turkmenistan", flag: "🇹🇲" },
	{ code: "TC", name: "Turks and Caicos Islands (the)", flag: "🇹🇨" },
	{ code: "TV", name: "Tuvalu", flag: "🇹🇻" },
	{ code: "UG", name: "Uganda", flag: "🇺🇬" },
	{ code: "UA", name: "Ukraine", flag: "🇺🇦" },
	{ code: "AE", name: "United Arab Emirates (the)", flag: "🇦🇪" },
	{ code: "GB", name: "United Kingdom of Great Britain and Northern Ireland (the)", flag: "🇬🇧" },
	{ code: "UM", name: "United States Minor Outlying Islands (the)", flag: "🇺🇲" },
	{ code: "US", name: "United States of America (the)", flag: "🇺🇸" },
	{ code: "UY", name: "Uruguay", flag: "🇺🇾" },
	{ code: "UZ", name: "Uzbekistan", flag: "🇺🇿" },
	{ code: "VU", name: "Vanuatu", flag: "🇻🇺" },
	{ code: "VE", name: "Venezuela (Bolivarian Republic of)", flag: "🇻🇪" },
	{ code: "VN", name: "Viet Nam", flag: "🇻🇳" },
	{ code: "VG", name: "Virgin Islands (British)", flag: "🇻🇬" },
	{ code: "VI", name: "Virgin Islands (U.S.)", flag: "🇻🇮" },
	{ code: "WF", name: "Wallis and Futuna", flag: "🇼🇫" },
	{ code: "EH", name: "Western Sahara", flag: "🇪🇭" },
	{ code: "YE", name: "Yemen", flag: "🇾🇪" },
	{ code: "ZM", name: "Zambia", flag: "🇿🇲" },
	{ code: "ZW", name: "Zimbabwe", flag: "🇿🇼" },
	{ code: "AX", name: "Åland Islands", flag: "🇦🇽" }
];
function CountrySelector(
    {value, onValueChange, disabled}: CountrySelectedProps
) {
    const selectedCountry = countryList.find((country) => country.code === value) || countryList[0]
  return (
    <DropdownMenu>
        <DropdownMenuTrigger asChild>
<Button
variant="outline"
disabled={disabled}
className='h-14 px-4 justify-between min-w-[140px] bordr-2 border-blue-200 dark:border-blue-800 hover:border-blue-500 dark:hover:border-blue-400 bg-white/80 dark:bg-gray-900/80 backdrop-blur-sm shadow-sm'
>
<div className='flex items-center gap-2'>
<span className='text-lg'>{selectedCountry.flag}</span>
<span className='font-medium'>{selectedCountry.code}</span>
</div>
<ChevronDown className='h-4 w-4 opacity-50' />


</Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent
        align='start' className='w-[280px] max-h-[300px] overflow-y-auto'
        >
{countryList.map((country) => (
    <DropdownMenuItem
    key={country.code}
    onClick={() => onValueChange(country.code)}
className='flex items-center gap-3 cursor-pointer'
    >
<span className='text-lg'>{country.flag}</span>
<div className='flex flex-col'>
    <span className='font-medium'>{country.name}</span>
<span className='text-xs text-muted-foreground'>
{country.code}
</span>
</div>
    </DropdownMenuItem>
))}
        </DropdownMenuContent>
    </DropdownMenu>
  )
}

export default CountrySelector